package com.hansen.customview.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.hansen.customview.mpandroidchart.VideoDateInfoBean;

import com.hansen.customview.greendao.VideoDateInfoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoDateInfoBeanDaoConfig;

    private final VideoDateInfoBeanDao videoDateInfoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoDateInfoBeanDaoConfig = daoConfigMap.get(VideoDateInfoBeanDao.class).clone();
        videoDateInfoBeanDaoConfig.initIdentityScope(type);

        videoDateInfoBeanDao = new VideoDateInfoBeanDao(videoDateInfoBeanDaoConfig, this);

        registerDao(VideoDateInfoBean.class, videoDateInfoBeanDao);
    }
    
    public void clear() {
        videoDateInfoBeanDaoConfig.clearIdentityScope();
    }

    public VideoDateInfoBeanDao getVideoDateInfoBeanDao() {
        return videoDateInfoBeanDao;
    }

}
